### PR TITLE
page edit

### LINKED ISSUE #11: Edits-to-webpage
Fixing typos, adding proofread text etc.

### PR DESCRIPTION
**Pull request by salinisenthil**
#11

### CODE REVIEW

**Comment by pskeshu** [comment]
your commit messages need not have the issue number. just a brief message on the commit will do.

**Comment by subindevs** [comment]
@salinisenthil Thanks for the corrections, can you please make the changes in [markdown](https://github.com/ndsystems/ndsystems-hugo-website/blob/3-try-minimal-theme/ndsystems/content/intern.md) , web pages here are generated using these markdown files.

**Comment by pskeshu** [comment]
> @salinisenthil Thanks for the corrections, can you please make the changes in [markdown](https://github.com/ndsystems/ndsystems-hugo-website/blob/3-try-minimal-theme/ndsystems/content/intern.md) , web pages here are generated using these markdown files.

In that case, it would be better to close this PR and create a new one, no? @subindevs 

Sorry, @salinisenthil, I didn't know that these html could be generated from the .md files. :worried:

**Comment by subindev-d** [comment]
> > @salinisenthil Thanks for the corrections, can you please make the changes in [markdown](https://github.com/ndsystems/ndsystems-hugo-website/blob/3-try-minimal-theme/ndsystems/content/intern.md) , web pages here are generated using these markdown files.
> 
> In that case, it would be better to close this PR and create a new one, no? @subindevs
> 
> Sorry, @salinisenthil, I didn't know that these html could be generated from the .md files.

no worries, yes, that would be better.

**Comment by subindevs** [comment]
> > @salinisenthil Thanks for the corrections, can you please make the changes in [markdown](https://github.com/ndsystems/ndsystems-hugo-website/blob/3-try-minimal-theme/ndsystems/content/intern.md) , web pages here are generated using these markdown files.
> 
> In that case, it would be better to close this PR and create a new one, no? @subindevs
> 
> Sorry, @salinisenthil, I didn't know that these html could be generated from the .md files. worried

Yes, creating a new pr is better

**Comment by pskeshu** [comment]
I'm closing this PR in that case

**Pull request closed without merging**
